env:
  - distro: debianjessie
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml
  - distro: ubuntutrusty
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml
  - distro: ubuntuxenial
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml

services:
  - docker

before_install:
  - docker pull jebovic/${distro}-ansible:latest

script:
  # run container
  - container_id=$(mktemp)
  - docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} jebovic/${distro}-ansible:latest "${init}" > "${container_id}"
  # syntax checking
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} --syntax-check
  # test role
  - docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook}
  # test role idempotence
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # test role tasks
  - >
    docker exec --tty "$(cat ${container_id})" env TERM=xterm ls /home
    | grep ops
    && (echo 'Home directory for user exists' && exit 0)
    || (echo 'User ops has no home' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: ODKPFEbjRFuYFHfTos79jFdQJZHTDX81rpwAJqfMH8psdPOIA7aA1ZpO0yPBOPgeFjpKr8bwrNjVKuF6mzQEoTfHHIldSp8BysPc9Wfbv8amjfpdyGSMYOqeHFzGsVSfPoJC+vpt+Q5tqHq7tOZsiaz0mHBVHrbtz/ix84Ro+L+/2l/QvJWjKYDixF9CZGQ20hlLpbK2/7TA6cKz2w5D2hAM7W++OwgXeWFohBWGYTewXsn3ORpVkjxfx8ePvua+Pd6/Wru3NwjKguEvU8QioG7sSOYxESQS5HAA8cQETOSVHtOxjXg2qh+HGLRz8AtQZgVibN3BwnA66bK23pdXn2BR7nSe1aD/YHuDz5VD3LPHE+heORAeVd7Kv3aTfPHUOsxIz8D/1/jEJmFOSyS6HfGGc64p+F76ixwqGU2NazF10D1S8LN0xHMp4e4Le+1WhCBt0tWfLOi5bF5n44gAzObqqeEvZds/txRQWCMp0xPdUMukH6iOn7OM4XD2ZvKeVAsm198QLDt1KL0dfcVzsYktOuYWeeVVBf67H97Nl2+Dro27SfRZ/clwF35qmxVmM08YBL7/VfD/ecthlbUx3DNXj8B0O+QIi5X9gnB3uOYGGAiVdqVboyv3bjvdWFwElzKyJqi/lJ7cv55xQ9ZnIr1N6C6kNLk5nMtV7ZOTr7g=
